//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatMonAn_Cloud.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int ID_DonHang { get; set; }
        public int ID_TaiKhoan { get; set; }
        public int ID_NhaHang { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> TrangThai { get; set; }
    }
}
