//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatMonAn_Cloud.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaBan
    {
        public int ID_GiaBan { get; set; }
        public int ID_MonAn { get; set; }
        public string GiaBan1 { get; set; }
        public string GiaKhuyenMai { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
    }
}
