//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatMonAn_Cloud.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loai
    {
        public int ID_LoaiMonAn { get; set; }
        public string Tên { get; set; }
        public string MoTa { get; set; }
    }
}
