//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatMonAn_Cloud.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaHang
    {
        public int ID_NhaHang { get; set; }
        public string TenNhaHang { get; set; }
        public string DiaChi { get; set; }
        public string ViTri { get; set; }
        public string SoDienThoai { get; set; }
        public string MoTa { get; set; }
    }
}
