//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatMonAn_Cloud.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int ID_TaiKhoan { get; set; }
        public string TenTaiKhoan { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string TienNap { get; set; }
        public string MatKhau { get; set; }
        public Nullable<bool> Online { get; set; }
    }
}
